### ISSUE TITLE
Doesn't work on 3.4 Symfony

### ISSUE THREAD

**Issue by jchesne** [borsaco/TelegramBotApiBundle#1]
It's seems that since the update we can not use this repo for Symfony 3.4, is it an error ?

**Comment by seddighi78** [comment]
I think it worked but if you have problem with this open issues to fix this

**Comment by jchesne** [comment]
Inside the composer.json you specified only for symfony 4.2 that's why i can not install it. Is used to use this API for my website, and now i can not use it anymore..
https://github.com/borsaco/TelegramBotApiBundle/blob/master/composer.json#L20

**Comment by seddighi78** [comment]
Ok I will fix this thank you for checking.

**Comment by jchesne** [comment]
Thanks man, i really enjoy your repo btw ! (do not forget to update composer ;) )

**Comment by seddighi78** [comment]
I will update it very soon. Don't worry about it ;)

**Comment by seddighi78** [comment]
fixed you can use it with Symfony 3.4. if you have a problem post it here. thanks
