### ISSUE TITLE
Can not use it via arguments in my sercices

### ISSUE THREAD

**Issue by jchesne** [borsaco/TelegramBotApiBundle#2]
I used to do :

arguments:
      - "@telegram_bot_api"

But now it's seems not possible:

 The service "myservice" has a dependency on a non-existent service "telegram_bot_api".

**Comment by seddighi78** [comment]
Use the class namespace instead of alias or input of construct function to use autowire .

**Comment by jchesne** [comment]
Ok right, i have done like this :

```
arguments:
      - '@Borsaco\TelegramBotApiBundle\Service\Bot'
```

Thanks a lot !
