### ISSUE TITLE
symfony 4.3 incomaptible composer

### ISSUE THREAD

**Issue by DaWulli** [borsaco/TelegramBotApiBundle#3]
is this bundle really incompatible with symfony 4.3?
otherwise the composer.json is very restrictive and it is not possible to run composer with symfony 4.3.

`Problem 1
    - Installation request for borsaco/telegram-bot-api-bundle ^1.0 -> satisfiable by borsaco/telegram-bot-api-bundle[1.0.0].
    - borsaco/telegram-bot-api-bundle 1.0.0 requires symfony/framework-bundle ^3.4 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it`

current framework-bundle is 4.3.2

**Comment by DaWulli** [comment]
#4

**Comment by seddighi78** [comment]
Solved
