### ISSUE TITLE
not enough to start

### ISSUE THREAD

**Issue by cybernet** [borsaco/TelegramBotApiBundle#6]
Can you provide more info about this project ?
First of all, I can't find the path for the hook, neither a tool to set it ...

**Comment by seddighi78** [comment]
make a route in your project for example `/bot/webhook` and use `$updateArray = $firstBot()->getWebhookUpdate();` on route controller for get webhook updates. the `$updateArray` is update from telegram.

```
/**
 * @Route("/bot/webhook")
*/
public function webhook(Bot $bot)
{
    $updateArray = $bot->getBot('my_bot')->getWebhookUpdate();
}
```

**Comment by seddighi78** [comment]
@cybernet Is your problem solved?

**Comment by cybernet** [comment]
yeah, solved it. i’ve found another project :)
getWebHook is outdated on 4.4
