### ISSUE TITLE
Attempted to load class "Kernel" from namespace "App"

### ISSUE THREAD

**Issue by jchesne** [borsaco/TelegramBotApiBundle#7]
Recently i encounter this error in fresh symfony 3.4 install:

`PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "Kernel" from namespace "App".
`

More specificaly on this line : 
`vendor/borsaco/telegram-bot-api-bundle/DependencyInjection/Configuration.php on line 16`

**Comment by seddighi78** [comment]
witch version of the bundle do you use?

**Comment by jchesne** [comment]
Version 1.0.3

**Comment by seddighi78** [comment]
Sorry, I have no time to check and test. Please use `dev-master` instead of this version if worked tell me to change the version and new release. 
thanks
