### ISSUE TITLE
[EXEMPLE] sendMediaGroup exemple

### ISSUE THREAD

**Issue by bennukem** [borsaco/TelegramBotApiBundle#8]
Hello,

Everything is working very well except sendMediaGroup I can't find a good way.
I would like to send a bunch of 2-3 images but never working, always a conflict between with the media type

So if someone can give me an example. I am under symfony 5.x

**Comment by seddighi78** [comment]
Hello,
I apologize for the late reply
Has your problem been resolved?

**Comment by bennukem** [comment]
Hi,
Do not apologize, i feel lucky someone reply. Even late.
I didn't solve so I put on side for the moment.
I think I will have new try this week

**Comment by seddighi78** [comment]
Can you please share your controller or codes
