### ISSUE TITLE
where i can find file for add my api ?

### ISSUE THREAD

**Issue by faustgete** [borsaco/TelegramBotApiBundle#9]
Hello. I'm installer Via Composer (composer require borsaco/telegram-bot-api-bundle).
Next:
Configure the bundle
This bundle was designed to just work out of the box. The only thing you have to configure in order to get this bundle up and running is your bot token. config/packages/telegram.yaml

but i cant find this file at the specified path - # config/packages/telegram.yaml

**Comment by seddighi78** [comment]
Hello 
This project is the Symfony framework bundle if you want to use a telegram bot SDK standalone you may use this package(https://github.com/irazasyed/telegram-bot-sdk).
if you are using Symfony framework that file stored in the `config` directory

**Comment by seddighi78** [comment]
Hello @faustgete 
is your problem solved?

**Comment by seddighi78** [comment]
Closed for inactivity.
